# Generated by Django 3.1 on 2020-09-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_register_attemptcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='attemptcount',
            new_name='que',
        ),
    ]
