# Generated by Django 3.1 on 2020-09-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200903_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='quelist',
            field=models.CharField(default='individual', max_length=255),
        ),
    ]
