# Generated by Django 3.1 on 2020-09-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200903_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='quelist',
            field=models.TextField(default='individual', max_length=255),
        ),
    ]
