# Generated by Django 3.1 on 2020-09-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200903_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='quelist',
            field=models.TextField(default='[1,2]', max_length=255),
        ),
    ]
