# Generated by Django 3.1 on 2020-09-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200903_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='quelist',
            field=models.TextField(default='[]', max_length=255),
        ),
    ]
