# Generated by Django 3.1 on 2020-09-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200929_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='extra_time',
            field=models.IntegerField(default=0),
        ),
    ]
