# Generated by Django 3.1 on 2020-09-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_register_extra_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='time_rem',
            field=models.IntegerField(default=1680),
        ),
    ]
