# Generated by Django 3.1 on 2020-10-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20201017_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='marks',
            field=models.IntegerField(default=1),
        ),
    ]
