# Generated by Django 3.1 on 2020-10-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20201018_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='flags',
            new_name='flag',
        ),
    ]
