# Generated by Django 3.1 on 2020-10-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20201019_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='quefulllist',
            field=models.TextField(default='[]', max_length=255),
        ),
    ]
