# Generated by Django 3.1 on 2020-10-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20201020_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='freezebar',
            field=models.BooleanField(default=False),
        ),
    ]
