# Generated by Django 3.1 on 2020-10-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_register_freezebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='freezetimestart',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
