# Generated by Django 3.1 on 2020-10-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_register_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='visionlst',
            field=models.TextField(default='[]', max_length=255),
        ),
    ]
