# Generated by Django 3.0.8 on 2020-10-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_register_visionlst'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='predicted_score',
            field=models.IntegerField(default=0),
        ),
    ]
