# Generated by Django 3.1 on 2020-10-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_register_predicted_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='logouttime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
