# Generated by Django 3.1 on 2020-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_auto_20201027_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='correct_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
