# Generated by Django 3.1 on 2021-01-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20210112_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='get_chance',
            field=models.BooleanField(default=True),
        ),
    ]
