# Generated by Django 3.1 on 2021-01-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_register_get_chance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='get_chance',
        ),
    ]
