# Generated by Django 3.1 on 2021-01-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_remove_register_get_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='get_chance',
            field=models.IntegerField(default=0),
        ),
    ]
