# Generated by Django 3.1 on 2021-01-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_register_get_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='freezeflag',
            field=models.BooleanField(default=False),
        ),
    ]
