# Generated by Django 3.1 on 2021-01-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_register_freezeflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='freezeflag',
            field=models.IntegerField(default=0),
        ),
    ]
