# Generated by Django 3.1 on 2021-01-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_register_freezesec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='freezeflag',
        ),
        migrations.RemoveField(
            model_name='register',
            name='freezesec',
        ),
    ]
