# Generated by Django 3.1 on 2021-01-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_auto_20210116_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='refresh',
            field=models.IntegerField(default=0),
        ),
    ]
