# Generated by Django 3.1 on 2021-01-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_register_refresh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='refresh',
            new_name='freezeflag',
        ),
    ]
