# Generated by Django 3.1 on 2021-01-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_auto_20210117_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='refresh',
            field=models.IntegerField(default=0),
        ),
    ]
