# Generated by Django 3.1 on 2021-01-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_register_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='permit',
            field=models.IntegerField(default=0),
        ),
    ]
