# Generated by Django 3.1 on 2021-01-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_register_permit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='permit',
        ),
    ]
