# Generated by Django 3.1 on 2021-01-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_remove_register_permit'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='permit',
            field=models.IntegerField(default=1),
        ),
    ]
